theme: jekyll-theme-minimal
logo: ./doc/LYK.jpg
title: Yuke Lou's HomePage
description: Thanks for visiting my homepage and welcome to contact me at:<br /><br /><a href="mailto:louyuke@pku.edu.cn">📮 louyuke@pku.edu.cn</a><br />
